### PR TITLE
Enable sourcemap

### PR DESCRIPTION
**Pull request by yhsiang**
This branch is not ready to merge, please wait for LiveScript 1.3.2 release.

### CODE REVIEW

**Comment by tomchentw** [comment]
Looks good

**Comment by tomchentw** [comment]
@yhsiang please update PR

**Comment by darrrk** [comment]
:+1:

**Comment by tomchentw** [comment]
PRPR

**Comment by yhsiang** [comment]
I updated my PR, sorry for late doing this.

**Comment by tomchentw** [comment]
BIG thanks to @yhsiang's contribution!

**Comment by tomchentw** [comment]
Published as [v2.4.0](https://github.com/tomchentw/gulp-livescript/releases/tag/v2.4.0)

**Pull request merged**
